### ISSUE TITLE
Cringe

### ISSUE THREAD

**Issue by DerSchokolo** [PanischerPublishing/WonderItems#1]
Ur code is cringe or i will dos u

**Comment by PanischerPublishing** [comment]
Do you have a problem?

Am Di., 23. Feb. 2021 um 12:48 Uhr schrieb DerSchokolo <
notifications@github.com>:

**Comment by DerSchokolo** [comment]
Glatze

**Comment by PanischerPublishing** [comment]
Now I report you at GitHub :=)

Good luck!

Am Mi., 24. Feb. 2021 um 08:22 Uhr schrieb DerSchokolo <
notifications@github.com>:
